### Get list of items
GET http://localhost:9090/api/v1/item

### Get specific item
GET http://localhost:9090/api/v1/item/1

### Create new todo
POST http://localhost:9090/api/v1/item
Content-Type: application/json; charset=utf-8

{
    "title": "Test title 2",
    "description": "Test description 2",
    "date_due": "2026-08-30 00:00:00.000",
    "date_added": "2026-07-29T00:00:00+02:00",
    "date_updated": "2026-07-29T00:00:00+02:00",
    "IsDone": false
}

### Update todo
PUT http://localhost:9090/api/v1/item/4
Content-Type: application/json; charset=utf-8

{
    "id": 4,
    "title": "Test title 4",
    "description": "Test description 4",
    "date_due": "2026-08-30 00:00:00.000",
    "date_added": "2026-07-29T00:00:00+02:00",
    "date_updated": "2026-07-29T00:00:00+02:00",
    "IsDone": false
}

### Delete todo
DELETE http://localhost:9090/api/v1/item/4
Content-Type: application/json; charset=utf-8